spring.application.name=budget-track
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
server.port=8080
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# spring.ai.openapi.chat.options.model=gpt-4.1
#spring.ai.openapi.api-key=myKey